---
title: "SDWIS_code1"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

## Load Relevant Packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(tidyverse)
library(sf)
library(raster)
library(readxl)
library(fs)
library(stringi)
library(lubridate)
library(units)
library(plotly)
library(cowplot)
library(openxlsx)
library(xml2)
library(censusxy)
```

## Load Raw SDWIS Data

```{r}
## download water system detail, which contains address information
## from EPA SDWIS API

SDWIS_active_cws <- fread("https://data.epa.gov/efservice/WATER_SYSTEM/PWS_ACTIVITY_CODE/A/PWS_TYPE_CODE/CWS/ROWS/0:99999/CSV", colClasses = "character")
```

## Prepare SDWIS data for geocoder

```{r}
## PO Box similar strings for filtering out
PO_Box_Strings <- ("P.O. BOX|PO Box|P O Box|P. O. BOX|P.O.|
PO DRAWER|POST OFFICE BOX|POST OFFICE DRAWER")

## start with raw sdwis data
SDWIS_geocoder <- SDWIS_active_cws %>%
  ## select only the address columns and PWSID
  select(PWSID, ADDRESS_LINE1:ZIP_CODE, STATE_CODE) %>%
  ## combine address line 1 and address line 2 columns
  unite(STREET_ADDRESS, ADDRESS_LINE1:ADDRESS_LINE2, sep = " ", na.rm = T) %>%
  ## filter for addresses without a PO Box
  filter(!grepl(PO_Box_Strings, STREET_ADDRESS, ignore.case = T)) %>%
  ## reorder columns to be street, city, state, zip
  relocate(STATE_CODE, .before = ZIP_CODE)

## geocoder can only take 10,000 addresses at a time, so split into three dataframes
SDWIS_geocoder_1 <- slice(SDWIS_geocoder, 1:10000)
SDWIS_geocoder_2 <- slice(SDWIS_geocoder, 10001:20000)
SDWIS_geocoder_3 <- slice(SDWIS_geocoder, 20001:length(SDWIS_geocoder$PWSID))
```

## Write csvs ready to geocode

```{r}
fwrite(SDWIS_geocoder_1, "./centroid_analysis/output/SDWIS_addresses_1.csv",
       col.names = F)
fwrite(SDWIS_geocoder_2, "./centroid_analysis/output/SDWIS_addresses_2.csv",
       col.names = F)
fwrite(SDWIS_geocoder_3, "./centroid_analysis/output/SDWIS_addresses_3.csv",
       col.names = F)
```

## Census Geocoder API

```{r}
## use censusxy package to access census geocoder
## geocode 500 addresses at a time

## split data into batches of 500
batches <- split(SDWIS_geocoder, (seq(nrow(SDWIS_geocoder))-1) %/% 500 )

## initialize results dataframe
SDWIS_geocode_results <- cxy_geocode(batches[[1]],
                                    street = "STREET_ADDRESS",
                                    city = "CITY_NAME",
                                    state = "STATE_CODE",
                                    zip = "ZIP_CODE",
                                    class = "dataframe",
                                    output = "full")

for (i in 2:length(batches)) {
  print(i)
  ## geocode
  temp <- cxy_geocode(batches[[i]],
                      street = "STREET_ADDRESS",
                      city = "CITY_NAME",
                      state = "STATE_CODE",
                      zip = "ZIP_CODE",
                      class = "dataframe",
                      output = "full")
  ## combine geocoded with all results
  SDWIS_geocode_results <- bind_rows(SDWIS_geocode_results, temp)
}

## write temporary results to return to later
fwrite(SDWIS_geocode_results,
       "./centroid_analysis/output/SDWIS_geocode_results_temp.csv")
```

## Rerun Geocoder, removing name from no match addresses

```{r}
## first pass matches
SDWIS_geocode_match <- SDWIS_geocode_results %>%
  filter(cxy_status == "Match")

## first pass no matches and ties
SDWIS_geocode_nomatch <- SDWIS_geocode_results %>%
  filter(cxy_status != "Match") %>%
  ## remove names in front of street number from street address column
  mutate(STREET_ADDRESS = sub("^\\D+(\\d)", "\\1", STREET_ADDRESS))

## rerun geocoder on cleaned no match addresses

## split data into batches of 500
batches_2 <- split(SDWIS_geocode_nomatch,
                   (seq(nrow(SDWIS_geocode_nomatch))-1) %/% 500 )

## initialize results dataframe
SDWIS_geocode_results_2 <- cxy_geocode(batches_2[[1]],
                                    street = "STREET_ADDRESS",
                                    city = "CITY_NAME",
                                    state = "STATE_CODE",
                                    zip = "ZIP_CODE",
                                    class = "dataframe",
                                    output = "full")

for (i in 2:length(batches_2)) {
  print(i)
  ## geocode
  temp <- cxy_geocode(batches_2[[i]],
                      street = "STREET_ADDRESS",
                      city = "CITY_NAME",
                      state = "STATE_CODE",
                      zip = "ZIP_CODE",
                      class = "dataframe",
                      output = "full")
  ## combine geocoded with all results
  SDWIS_geocode_results_2 <- bind_rows(SDWIS_geocode_results_2, temp)
}

## Combine first pass matches with second pass results
SDWIS_geocode_clean <- bind_rows(SDWIS_geocode_match,
                                 SDWIS_geocode_results_2)
```



```{r}
#Set working directory
setwd("/Users/lesliebernal/R_data")

#Import Water System Detail database
Water_System_Detail <- read.csv("~/R_data/Water_System_Detail.csv", header=FALSE)
#View(Water_System_Detail)
```


```{r}
#Delete columns
#To be able to use the geocoder, the input file needs to have the following fields only: ID, Address (Street number and name of street), City, State, and Zip Code.

#library(dplyr)
WSD = select(Water_System_Detail, -c(2:29, 35:37))
```

```{r}
#Merge columns
#There are two Address columns, we need to merge them so we only have one.
WSD = unite(WSD, Address, c(2,3))
```

```{r}
#Filter data
#Delete rows that include PO Boxes, or N/A cells
WSD <- WSD %>%
filter(!grepl("P.O. BOX", Address, ignore.case = T),
       !grepl("PO BOX", Address, ignore.case = T), 
       !grepl("PO Box", Address, ignore.case = T),
       !grepl("P O Box", Address, ignore.case = T),
       !grepl("Box", Address, ignore.case = T),
       !grepl("P. O. BOX", Address, ignore.case = T),
       !grepl("P.O.", Address, ignore.case = T),
       !grepl("PO DRAWER", Address, ignore.case = T),
       !grepl("POST OFFICE BOX", Address, ignore.case = T),
       !grepl("POST OFFICE DRAWER", Address, ignore.case = T),
       !grepl("POB", Address, ignore.case = T),
       !grepl("N A", Address, ignore.case = T))
```

```{r}
#Split dataframe according to geocoder requirements
#The Census Geocoder only allows CSV documents with 10,000 values max. Depending on the total of observation points, you need to split the dataframe.
WSD_a <- slice(WSD[1:9990,], .preserve = TRUE )
WSD_b <- slice(WSD[9991:19981,], .preserve = TRUE)
WSD_c <- slice(WSD[19982:28315,], .preserve = TRUE)
```

```{r}
#Delete columns name
#File WSD_a
x1<-WSD_a$V1
x2<-WSD_a$Address
x3<-WSD_a$V32
x4<-WSD_a$V33
x5<-WSD_a$V34
WSD_a<-data.frame(x1,x2,x3,x4,x5)
names(WSD_a)<- NULL

#File WSD_b
x1<-WSD_b$V1
x2<-WSD_b$Address
x3<-WSD_b$V32
x4<-WSD_b$V33
x5<-WSD_b$V34
WSD_b<-data.frame(x1,x2,x3,x4,x5)
names(WSD_b)<- NULL

#File WSD_c
x1<-WSD_c$V1
x2<-WSD_c$Address
x3<-WSD_c$V32
x4<-WSD_c$V33
x5<-WSD_c$V34
WSD_c<-data.frame(x1,x2,x3,x4,x5)
names(WSD_c)<- NULL
```

```{r}
#Delete first row (only applies to first dataframe created, in this case, WSD_a)
WSD_a <- WSD_a[-c(1), ] 
```

```{r}
#Create CSV files for multiple dataframes
myList <- list(WSD_a = WSD_a, 
               WSD_b = WSD_b,
               WSD_c = WSD_c)
mapply(write.csv, row.names=FALSE, myList, file=paste0(names(myList), '.csv'))


# Input files WSD_a.csv, WSD_b.csv, and WSD_c.csv into Geocoder
```


